name: "Terraform Valida Modulo"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  terraform:
      uses: "EzzioMoreira/cicd_centralizado/.github/workflows/terraform_valida_modulo.yaml@feat/add-actions-terraform"
      with: 
        tf_version: "1.0.0"
        os_version: "ubuntu-20.04"
      secrets:
        token: ${{ secrets.TOKEN }}
